### ISSUE TITLE
Invalid key exception, while private and public key is there

### ISSUE THREAD

**Issue by naufalscofield** [miladrahimi/php-jwt#10]
Hey, can you please help me? i found this error with NULL message

I use on Codeigniter and Windows OS, i'm little bit confused because in my MacOs, it's worked, and i dont change anything on the source code and the .pem file of public and private key.

![e73aa7f9-723c-41e5-a003-63a02a6c0b10](https://user-images.githubusercontent.com/38066867/124854298-5577b700-dfd1-11eb-8b4f-5f0f10bb566b.jpeg)

**Comment by miladrahimi** [comment]
could you please paste all the error here?

**Comment by miladrahimi** [comment]
Please use the newer version `v2.1.4` and let me know if the issue is fixed or not.
