### ISSUE TITLE
Allow keys to be instantiated from strings rather than only from files

### ISSUE THREAD

**Issue by tremby** [miladrahimi/php-jwt#17]
I am grabbing the public key I want to verify a token against from the web. Currently as far as I can tell with this library I'd need to save that to a file in order to pass that file path into `RsaPublicKey`'s constructor.

It'd be nice if I didn't need to do that middle step.

I'm a little confused about why the current behaviour is as it is, given how `openssl_pkey_get_public` works -- [its docs](https://www.php.net/manual/en/function.openssl-pkey-get-public.php) say that it supports various formats of inputs including a PEM string like I have or a filename in the format `file://path/to/file.pem` already, among a couple of others, so why not pass an argument straight through?

**Comment by tremby** [comment]
Current workaround is to extend the class. It's a shame `$resource` is private in the class I'm extending, or I could skip the getter method rather than shadowing the var.

```php
use MiladRahimi\Jwt\Cryptography\Keys\RsaPublicKey;
use MiladRahimi\Jwt\Exceptions\InvalidKeyException;

class RsaPublicKeyFlexible extends RsaPublicKey {
    /**
     * @var mixed Key file resource handler
     */
    private $_resource;

    /**
     * @throws InvalidKeyException
     */
    public function __construct($arg, ?string $id = null)
    {
        $this->_resource = openssl_pkey_get_public($arg);

        if ($this->_resource === false) {
            throw new InvalidKeyException(openssl_error_string());
        }

        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getResource()
    {
        return $this->_resource;
    }
}
```

**Comment by miladrahimi** [comment]
@tremby actually it's a good feature, you can create PR for it as you already investigated enough, otherwise I'll handle it soon and will release a new version for it

**Comment by tremby** [comment]
The way I would do it (pass straight through to `openssl_pkey_get_public`) would be a breaking change, since to continue to load from a file users' code would have to change to include the `file://` prefix. I could provide a patch if you tell me you're OK with that.

Otherwise I could just relax some of the "private" to "protected" to make my override a bit simpler.

**Comment by miladrahimi** [comment]
Included in release https://github.com/miladrahimi/php-jwt/releases/tag/v3.2.0

**Comment by tremby** [comment]
Thanks. It's working for me. Might I suggest documenting that it can be a string now in the readme.

**Comment by tremby** [comment]
I also note from looking at your diff (at least on RsaPublicKey which I'm using) that you're no longer running `realpath` on the string before trying to load that file. I think this could potentially be a breaking change for some users.

**Comment by miladrahimi** [comment]
Thanks for letting me know the issue.
New path released: https://github.com/miladrahimi/php-jwt/releases/tag/v3.2.2
Diff with previous version: https://github.com/miladrahimi/php-jwt/compare/v3.2.0...v3.2.2
