### ISSUE TITLE
Have the various exceptions inherit from a single exception type

### ISSUE THREAD

**Issue by tremby** [miladrahimi/php-jwt#18]
Right now all the exceptions inherit from `\Exception`. This means I have no way to catch specifically exceptions from this library, other than catching each separate possible exception type, and that's not maintainable.

If you had a (possibly abstract) base exception class and had all your other exceptions inherit from that, my error handling could be simpler, since I could catch that parent exception type.

**Comment by miladrahimi** [comment]
That's a good idea.

**Comment by miladrahimi** [comment]
New version is released: https://github.com/miladrahimi/php-jwt/releases/tag/v3.2.0

**Comment by tremby** [comment]
Thanks. It works for me.
