### ISSUE TITLE
Quick Start Sample Code Error

### ISSUE THREAD

**Issue by ScottKennedyAL** [miladrahimi/php-jwt#26]
I was attempting to copy/paste and run the sample code at the top of the documentation.  When I did that, I got an error that the class HmacKey could not be found.  When I added "use MiladRahimi\Jwt\Cryptography\Keys\HmacKey;" to the sample code the error was resolved.  Sharing this here in case anyone else runs into a similar issue.

**Comment by miladrahimi** [comment]
thanks for sharing the issue. It's added to the example.
