### ISSUE TITLE
Wrong condition

### ISSUE THREAD

**Issue by WalentinG** [miladrahimi/php-jwt#5]
Exp must be newer than now
https://github.com/miladrahimi/php-jwt/blob/333b2db8895c48b2717acd3d269b53f556078738/src/Validator/DefaultValidator.php#L21
but your NewerThan has incorrect behavior
https://github.com/miladrahimi/php-jwt/blob/333b2db8895c48b2717acd3d269b53f556078738/src/Validator/Rules/Required/GreaterThan.php#L32
Result: `time() > exp`, must be  `exp  > time()`

**Comment by miladrahimi** [comment]
Thanks for your report.
The bug is fixed now, you can update the package with composer update.
[https://github.com/miladrahimi/php-jwt/releases/tag/v1.1.4](v1.1.4)
